import { Product, Bundle } from "./types";

export const products: Product[] = [
  // Hooded Towels
  {
    id: "ht-001",
    name: "Muslin Hooded Towel - Strawberry",
    sku: "HT-MUS-STR",
    price: 21,
    category: "hooded-towels",
    subCategory: "Muslin",
    designs: ["Strawberry", "Cloudy"],
    ageGroups: ["3-6-months", "6-12-months", "1-2-years", "2-3-years", "3-4-years"],
    material: "100% Organic Cotton Muslin",
    description: "Soft comfort for your newborn's first days. Our hooded baby towel is made from soft quilted cotton, offering gentle care for delicate skin. Ideal for hospital essentials and everyday use.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/hooded-towel-1.jpg"],
    isOrganic: true,
    isBestSeller: true,
    inStock: true,
  },
  {
    id: "ht-002",
    name: "Knitted Hooded Towel - Cloudy",
    sku: "HT-KNT-CLD",
    price: 24,
    category: "hooded-towels",
    subCategory: "Knitted",
    designs: ["Strawberry", "Cloudy"],
    ageGroups: ["3-6-months", "6-12-months", "1-2-years"],
    material: "100% Organic Cotton Knit",
    description: "Cozy knitted hooded towel perfect for sensitive skin. Breathable fabric with adjustable wrap belt.",
    careInstructions: "Hand wash recommended",
    images: ["/images/products/hooded-towel-2.jpg"],
    isOrganic: true,
    inStock: true,
  },

  // Swaddles
  {
    id: "sw-001",
    name: "Organic Muslin Swaddle - Giraffe",
    sku: "SW-MUS-GIR",
    price: 18,
    category: "swaddles",
    designs: ["Giraffe", "Carrot", "Duck", "Watermelon", "Car", "Fruit"],
    ageGroups: ["0-3-months", "3-6-months"],
    material: "GOTS Certified Organic Cotton Muslin",
    description: "Our GOTS-certified organic muslin swaddles are made from carefully selected organic cotton and produced to high environmental and quality standards. Lightweight and breathable.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/swaddle-1.jpg"],
    isOrganic: true,
    isNew: true,
    inStock: true,
  },
  {
    id: "sw-002",
    name: "Organic Muslin Swaddle - Carrot",
    sku: "SW-MUS-CAR",
    price: 18,
    category: "swaddles",
    ageGroups: ["0-3-months", "3-6-months"],
    material: "GOTS Certified Organic Cotton Muslin",
    description: "Lightweight and breathable, they support good air circulation, help prevent overheating.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/swaddle-2.jpg"],
    isOrganic: true,
    inStock: true,
  },
  {
    id: "sw-003",
    name: "Organic Muslin Swaddle - Watermelon",
    sku: "SW-MUS-WML",
    price: 20,
    category: "swaddles",
    ageGroups: ["0-3-months", "3-6-months"],
    material: "GOTS Certified Organic Cotton Muslin",
    description: "Perfect for keeping your baby comfortably wrapped in style.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/swaddle-3.jpg"],
    isOrganic: true,
    inStock: true,
  },

  // Burp Cloths
  {
    id: "bc-001",
    name: "Soft Burp Cloth - Deer",
    sku: "BC-DER-001",
    price: 12,
    category: "burp-cloths",
    designs: ["Deer", "Dino", "Car", "Penguin", "Fruit", "Panda"],
    ageGroups: ["0-3-months", "3-6-months", "6-12-months"],
    material: "100% Organic Cotton",
    description: "Soft, absorbent, and durable. Gentle on delicate baby skin. Ideal for quick clean-ups and daily use.",
    careInstructions: "Machine wash warm",
    images: ["/images/products/burp-cloth-1.jpg"],
    isOrganic: true,
    isBestSeller: true,
    inStock: true,
  },

  // Blankets
  {
    id: "bl-001",
    name: "2-Layer Muslin Blanket",
    sku: "BL-2LY-001",
    price: 26,
    category: "blankets",
    subCategory: "2-Layer",
    ageGroups: ["0-3-months", "3-6-months", "6-12-months", "1-2-years", "2-3-years", "3-4-years"],
    material: "100% Organic Cotton Muslin",
    description: "Made from soft breathable muslin, these blankets provide gentle comfort while remaining lightweight and airy. Versatile for swaddling, cuddling, playtime, or travel use.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/blanket-1.jpg"],
    isOrganic: true,
    inStock: true,
  },
  {
    id: "bl-002",
    name: "6-Layer Premium Muslin Blanket",
    sku: "BL-6LY-001",
    price: 42,
    category: "blankets",
    subCategory: "6-Layer",
    ageGroups: ["0-3-months", "3-6-months", "6-12-months", "1-2-years"],
    material: "100% Organic Cotton Muslin",
    description: "Premium 6-layer muslin for maximum softness and warmth. Perfect for colder days.",
    careInstructions: "Machine wash cold, tumble dry low",
    images: ["/images/products/blanket-2.jpg"],
    isOrganic: true,
    isBestSeller: true,
    inStock: true,
  },

  // Night Suits
  {
    id: "ns-001",
    name: "Comfy Night Suit - Strawberry",
    sku: "NS-STR-001",
    price: 24,
    category: "night-suits",
    designs: ["Strawberry", "Cloudy"],
    ageGroups: ["3-6-months", "6-12-months", "1-2-years", "2-3-years"],
    material: "100% Organic Cotton",
    description: "Comfortable sleepwear for day and night. Made from soft breathable fabric to keep your baby comfortable during both sleep and play.",
    careInstructions: "Machine wash warm",
    images: ["/images/products/night-suit-1.jpg"],
    isOrganic: true,
    isNew: true,
    inStock: true,
  },

  // Shirts
  {
    id: "sh-001",
    name: "Classic Cotton Shirt - Monkey",
    sku: "SH-MON-001",
    price: 22,
    category: "shirts",
    designs: ["Monkey", "Blue", "Palm Tree", "Dino"],
    ageGroups: ["6-12-months", "1-2-years", "2-3-years", "3-4-years"],
    material: "Premium Organic Cotton",
    description: "Classic style with everyday comfort. Crafted from premium cotton and designed for breathable all-day wear.",
    careInstructions: "Machine wash cold",
    images: ["/images/products/shirt-1.jpg"],
    isOrganic: true,
    inStock: true,
  },

  // Kimono Sets
  {
    id: "ks-001",
    name: "Kimono Set - Green Giraffe",
    sku: "KS-GIR-001",
    price: 32,
    category: "kimono-sets",
    designs: ["Green Giraffe", "Pink Cow", "Yellow Dino", "Heart"],
    ageGroups: ["3-6-months", "6-12-months", "1-2-years"],
    material: "100% Organic Cotton",
    description: "Comfortable and practical for everyday wear. The kimono-style top allows easy dressing while remaining soft and breathable for sensitive skin.",
    careInstructions: "Machine wash warm",
    images: ["/images/products/kimono-1.jpg"],
    isOrganic: true,
    isBestSeller: true,
    inStock: true,
  },

  // Co-Ord Sets
  {
    id: "co-001",
    name: "Crinkle Co-Ord Set - Dino",
    sku: "CO-DIN-001",
    price: 30,
    category: "co-ord-sets",
    designs: ["Dino", "Heart", "Pink Stripe", "Blue Stripe"],
    ageGroups: ["6-12-months", "1-2-years", "2-3-years", "3-4-years"],
    material: "Breathable Crinkle Cotton",
    description: "Lightweight comfort with a relaxed summer style. Designed using breathable crinkle cotton to keep children cool and comfortable throughout the day.",
    careInstructions: "Machine wash cold",
    images: ["/images/products/coords-1.jpg"],
    isOrganic: true,
    isNew: true,
    inStock: true,
  },
];

export const bundles: Bundle[] = [
  {
    id: "bundle-001",
    name: "Everyday Outfit Set",
    description: "Affordable daily essentials bundle",
    products: [products.find(p => p.id === "ns-001")!, products.find(p => p.id === "bc-001")!],
    price: 30,
    originalPrice: 36,
    savings: 6,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Everyday Outfit Set (1 Night Suit + 1 Burp Cloth).",
  },
  {
    id: "bundle-002",
    name: "Playtime Set",
    description: "Daytime comfort and activity bundle",
    products: [products.find(p => p.id === "co-001")!, products.find(p => p.id === "sw-001")!],
    price: 42,
    originalPrice: 48,
    savings: 6,
    isFeatured: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Playtime Set (1 Co-Ord Set + 1 Swaddle).",
  },
  {
    id: "bundle-003",
    name: "Gift Outfit Set",
    description: "Premium gifting collection",
    products: [products.find(p => p.id === "ks-001")!, products.find(p => p.id === "bl-001")!],
    price: 48,
    originalPrice: 58,
    savings: 10,
    isPerfectGift: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Gift Outfit Set (1 Kimono Set + 1 Blanket).",
  },
  {
    id: "bundle-004",
    name: "Premium Baby Wardrobe Set",
    description: "Luxury complete wardrobe bundle",
    products: [
      products.find(p => p.id === "co-001")!,
      products.find(p => p.id === "ns-001")!,
      products.find(p => p.id === "sw-001")!,
      products.find(p => p.id === "bc-001")!,
    ],
    price: 72,
    originalPrice: 84,
    savings: 12,
    isPerfectGift: true,
    isFeatured: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Premium Baby Wardrobe Set.",
  },
  {
    id: "bundle-005",
    name: "Newborn Starter Set",
    description: "Hospital and newborn essentials",
    products: [products.find(p => p.id === "sw-001")!, products.find(p => p.id === "bc-001")!],
    price: 26,
    originalPrice: 30,
    savings: 4,
    isPerfectGift: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Newborn Starter Set.",
  },
  {
    id: "bundle-006",
    name: "Bath Time Set",
    description: "Bath and post-care essentials",
    products: [products.find(p => p.id === "ht-001")!, products.find(p => p.id === "bc-001")!],
    price: 30,
    originalPrice: 33,
    savings: 3,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Bath Time Set.",
  },
  {
    id: "bundle-007",
    name: "Everyday Essentials Set",
    description: "Best-value essentials collection",
    products: [
      products.find(p => p.id === "sw-001")!,
      products.find(p => p.id === "bc-001")!,
      products.find(p => p.id === "bl-001")!,
    ],
    price: 47,
    originalPrice: 56,
    savings: 9,
    isFeatured: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Everyday Essentials Set.",
  },
  {
    id: "bundle-008",
    name: "Comfort Set (Premium)",
    description: "High-end luxury comfort bundle",
    products: [
      products.find(p => p.id === "ht-001")!,
      products.find(p => p.id === "sw-001")!,
      products.find(p => p.id === "bc-001")!,
      products.find(p => p.id === "bl-002")!,
    ],
    price: 72,
    originalPrice: 85,
    savings: 13,
    isPerfectGift: true,
    isFeatured: true,
    whatsappTemplate: "Hello SamAira Creations, I would like to order the Comfort Set (Premium).",
  },
];

export const bestSellers = products.filter(p => p.isBestSeller);

export const newArrivals = products.filter(p => p.isNew);